# Generated by Django 4.2.8 on 2024-05-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outerapi', '0002_depositproducts_depositoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproducts',
            name='dcls_strt_day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='depositproducts',
            name='max_limit',
            field=models.IntegerField(null=True),
        ),
    ]
