# Generated by Django 4.2.8 on 2024-05-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outerapi', '0002_buydepositproduct_buysavingproduct_savingproducts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buydepositproduct',
            name='options',
        ),
        migrations.RemoveField(
            model_name='buysavingproduct',
            name='options',
        ),
        migrations.AddField(
            model_name='buydepositproduct',
            name='intr_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='buydepositproduct',
            name='intr_rate2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='buysavingproduct',
            name='intr_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='buysavingproduct',
            name='intr_rate2',
            field=models.FloatField(null=True),
        ),
    ]
