# Generated by Django 4.2.8 on 2024-05-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outerapi', '0003_depositproducts_dcls_strt_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproducts',
            name='dcls_strt_day',
            field=models.CharField(max_length=50),
        ),
    ]
