# Generated by Django 4.2.8 on 2024-05-20 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outerapi', '0004_alter_depositproducts_dcls_strt_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoptions',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='outerapi.depositproducts'),
        ),
    ]
