# Generated by Django 4.2.8 on 2024-05-21 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outerapi', '0007_alter_savingoptions_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoptions',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_options', to='outerapi.depositproducts'),
        ),
        migrations.AlterField(
            model_name='savingoptions',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_options', to='outerapi.savingproducts'),
        ),
    ]
