# Generated by Django 4.2.8 on 2024-05-21 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outerapi', '0008_alter_depositoptions_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingoptions',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='outerapi.savingproducts'),
        ),
    ]
