# Generated by Django 4.2.8 on 2024-05-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_age_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('0', '비공개'), ('1', '남성'), ('2', '여성')], default='0', max_length=255),
        ),
    ]
