# Generated by Django 4.2.8 on 2024-05-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='asset',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='goal',
            field=models.CharField(choices=[('비공개', '비공개'), ('남성', '남성'), ('여성', '여성')], default='무계획', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, default='무직', max_length=255),
        ),
    ]
