# Generated by Django 4.2.8 on 2024-05-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_asset_user_goal_user_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='goal',
            field=models.CharField(choices=[('무계획', '무계획'), ('안전형', '안전형'), ('수익형', '수익형')], default='무계획', max_length=255),
        ),
    ]
